name: macos-arm64

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        run: |
          git clone https://github.com/google/angle .
      - name: Fetch depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - name: Build
        run: |
          export PATH="$(pwd)/depot_tools:$PATH"
          python scripts/bootstrap.py
          gclient sync
          gn gen out/Release --args="is_debug=false target_cpu=\"arm64\" angle_build_all=false"
          autoninja -C out/Release
      - name: Pack
        run: |
          mkdir angle-macos-arm64
          mkdir angle-macos-arm64/dist
          rm -rf out/Release/gen
          rm -rf out/Release/obj
          rm -rf out/Release/args.gn
          rm -rf out/Release/build.ninja
          rm -rf out/Release/build.ninja.d
          rm -rf out/Release/toolchain.ninja
          find out/Release -name "*.TOC" -delete
          mv -f out/Release/* angle-macos-arm64/dist/
          cp -rf include angle-macos-arm64/
          find angle-macos-arm64 -name ".clang-format" -delete
          find angle-macos-arm64 -name "*.md" -delete
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: angle-macos-arm64
          path: angle-macos-arm64
