name: windows-x86

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-windows-x86:
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        run: |
          git clone https://github.com/google/angle .
      - name: Fetch depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - name: Build
        shell: cmd
        run: |
          set PATH=%cd%\depot_tools;%PATH%
          set DEPOT_TOOLS_WIN_TOOLCHAIN=0
          set vs2019_install=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
          set WINDOWSSDKDIR=C:\Program Files (x86)\Windows Kits\10
          cmd /c gclient
          cmd /c python scripts/bootstrap.py
          cmd /c gclient sync
          cmd /c gn gen out/Release --args="is_debug=false target_cpu=\"x86\" angle_build_all=false"
          cmd /c autoninja -C out/Release
      - name: Pack
        shell: bash
        run: |
          mkdir angle-windows-x86
          mkdir angle-windows-x86/dist
          rm -rf out/Release/cdb
          rm -rf out/Release/gen
          rm -rf out/Release/obj
          rm -rf out/Release/args.gn
          rm -rf out/Release/build.ninja
          rm -rf out/Release/build.ninja.d
          rm -rf out/Release/toolchain.ninja
          rm -rf out/Release/environment.*
          find out/Release -name "*.pdb" -delete
          mv -f out/Release/* angle-windows-x86/dist/
          cp -rf include angle-windows-x86/
          find angle-windows-x86 -name ".clang-format" -delete
          find angle-windows-x86 -name "*.md" -delete
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: angle-windows-x86
          path: angle-windows-x86
